### ISSUE TITLE
question: how to install

### ISSUE THREAD

**Issue by ghost** [ebolefeysot/RomcenterPlugins#2]
How do we install those plugins?

Thx

**Comment by ebolefeysot** [comment]
Hi, these plugins are used by romcenter to identify a game from the rom.
You simply copy the dll produced in the '/plugin' folder of romcenter installation.
See here for more infos https://wiki.romcenter.com/wiki/doku.php?id=plugin

**Comment by ghost** [comment]
Can you maybe add a window to enable/disable plugins that are installed? (a checkbox)
